# Generated by Django 5.0.6 on 2024-06-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicallayergrouptreeitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Groupe de couche', 'verbose_name_plural': 'historical Groupes de couche'},
        ),
        migrations.AlterModelOptions(
            name='layergrouptreeitem',
            options={'ordering': ['ordering'], 'verbose_name': 'Groupe de couche', 'verbose_name_plural': 'Groupes de couche'},
        ),
    ]
